[workspace]
resolver = "2"
members = [ 
    "swap-cli",
    "swapd",
]

[workspace.dependencies]
clap = "4.5.23"
hex = "0.4.3"
prost = "0.13.3"
serde = "1.0.215"
serde_json = "1.0.133"
tokio = "1.42.0"
tonic = "0.12.3"
tonic-build = "0.12.3"
