[workspace]
resolver = "2"
members = [ 
    "swap-cli",
    "swapd",
]

[workspace.dependencies]
clap = "4.5.8"
hex = "0.4.3"
prost = "0.13.1"
serde = "1.0.207"
serde_json = "1.0.127"
tokio = "1.39.2"
tonic = "0.12.1"
tonic-build = "0.12.1"
