[package]
name = "swapd"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
bitcoin = "0.30.2"
clap = { version = "4.5.8", features = ["derive"] }
hex = "0.4.3"
lightning-invoice = "0.31.0"
prost = "0.13.1"
reqwest = { version = "0.12.5", features = ["json"] }
ring = "0.17.8"
serde = { version = "1.0.207", features = ["derive"] }
tokio = { version = "1.39.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.12.1"

[build-dependencies]
tonic-build = "0.12.1"
