# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swap_pb2 as swap__pb2

GRPC_GENERATED_VERSION = "1.66.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in swap_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class SwapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFundInit = channel.unary_unary(
            "/swap.Swapper/AddFundInit",
            request_serializer=swap__pb2.AddFundInitRequest.SerializeToString,
            response_deserializer=swap__pb2.AddFundInitReply.FromString,
            _registered_method=True,
        )
        self.AddFundStatus = channel.unary_unary(
            "/swap.Swapper/AddFundStatus",
            request_serializer=swap__pb2.AddFundStatusRequest.SerializeToString,
            response_deserializer=swap__pb2.AddFundStatusReply.FromString,
            _registered_method=True,
        )
        self.GetSwapPayment = channel.unary_unary(
            "/swap.Swapper/GetSwapPayment",
            request_serializer=swap__pb2.GetSwapPaymentRequest.SerializeToString,
            response_deserializer=swap__pb2.GetSwapPaymentReply.FromString,
            _registered_method=True,
        )


class SwapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFundInit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddFundStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSwapPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SwapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "AddFundInit": grpc.unary_unary_rpc_method_handler(
            servicer.AddFundInit,
            request_deserializer=swap__pb2.AddFundInitRequest.FromString,
            response_serializer=swap__pb2.AddFundInitReply.SerializeToString,
        ),
        "AddFundStatus": grpc.unary_unary_rpc_method_handler(
            servicer.AddFundStatus,
            request_deserializer=swap__pb2.AddFundStatusRequest.FromString,
            response_serializer=swap__pb2.AddFundStatusReply.SerializeToString,
        ),
        "GetSwapPayment": grpc.unary_unary_rpc_method_handler(
            servicer.GetSwapPayment,
            request_deserializer=swap__pb2.GetSwapPaymentRequest.FromString,
            response_serializer=swap__pb2.GetSwapPaymentReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "swap.Swapper", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("swap.Swapper", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Swapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFundInit(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.Swapper/AddFundInit",
            swap__pb2.AddFundInitRequest.SerializeToString,
            swap__pb2.AddFundInitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddFundStatus(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.Swapper/AddFundStatus",
            swap__pb2.AddFundStatusRequest.SerializeToString,
            swap__pb2.AddFundStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSwapPayment(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.Swapper/GetSwapPayment",
            swap__pb2.GetSwapPaymentRequest.SerializeToString,
            swap__pb2.GetSwapPaymentReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
