# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swap_pb2 as swap__pb2

GRPC_GENERATED_VERSION = "1.68.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in swap_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class TaprootSwapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSwap = channel.unary_unary(
            "/swap.TaprootSwapper/CreateSwap",
            request_serializer=swap__pb2.CreateSwapRequest.SerializeToString,
            response_deserializer=swap__pb2.CreateSwapResponse.FromString,
            _registered_method=True,
        )
        self.PaySwap = channel.unary_unary(
            "/swap.TaprootSwapper/PaySwap",
            request_serializer=swap__pb2.PaySwapRequest.SerializeToString,
            response_deserializer=swap__pb2.PaySwapResponse.FromString,
            _registered_method=True,
        )
        self.RefundSwap = channel.unary_unary(
            "/swap.TaprootSwapper/RefundSwap",
            request_serializer=swap__pb2.RefundSwapRequest.SerializeToString,
            response_deserializer=swap__pb2.RefundSwapResponse.FromString,
            _registered_method=True,
        )
        self.SwapParameters = channel.unary_unary(
            "/swap.TaprootSwapper/SwapParameters",
            request_serializer=swap__pb2.SwapParametersRequest.SerializeToString,
            response_deserializer=swap__pb2.SwapParametersResponse.FromString,
            _registered_method=True,
        )


class TaprootSwapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def PaySwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RefundSwap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SwapParameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_TaprootSwapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreateSwap": grpc.unary_unary_rpc_method_handler(
            servicer.CreateSwap,
            request_deserializer=swap__pb2.CreateSwapRequest.FromString,
            response_serializer=swap__pb2.CreateSwapResponse.SerializeToString,
        ),
        "PaySwap": grpc.unary_unary_rpc_method_handler(
            servicer.PaySwap,
            request_deserializer=swap__pb2.PaySwapRequest.FromString,
            response_serializer=swap__pb2.PaySwapResponse.SerializeToString,
        ),
        "RefundSwap": grpc.unary_unary_rpc_method_handler(
            servicer.RefundSwap,
            request_deserializer=swap__pb2.RefundSwapRequest.FromString,
            response_serializer=swap__pb2.RefundSwapResponse.SerializeToString,
        ),
        "SwapParameters": grpc.unary_unary_rpc_method_handler(
            servicer.SwapParameters,
            request_deserializer=swap__pb2.SwapParametersRequest.FromString,
            response_serializer=swap__pb2.SwapParametersResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "swap.TaprootSwapper", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("swap.TaprootSwapper", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class TaprootSwapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSwap(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.TaprootSwapper/CreateSwap",
            swap__pb2.CreateSwapRequest.SerializeToString,
            swap__pb2.CreateSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def PaySwap(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.TaprootSwapper/PaySwap",
            swap__pb2.PaySwapRequest.SerializeToString,
            swap__pb2.PaySwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RefundSwap(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.TaprootSwapper/RefundSwap",
            swap__pb2.RefundSwapRequest.SerializeToString,
            swap__pb2.RefundSwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SwapParameters(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/swap.TaprootSwapper/SwapParameters",
            swap__pb2.SwapParametersRequest.SerializeToString,
            swap__pb2.SwapParametersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
